### ISSUE TITLE
Add back support for the sidebar by default

### ISSUE THREAD

**Issue by jamesls** [guzzle/guzzle_sphinx_theme#15]
I noticed when I upgraded to the latest theme (I was coming from a really old 0.3.x release) that the sidebar is no longer displayed by default.

For example, if I build an empty sphinx project using their built in theme I get:

![screen shot 2015-04-04 at 3 15 41 pm](https://cloud.githubusercontent.com/assets/368057/6994889/6feb3e08-dade-11e4-95cb-5643386cb30b.png)

When I used version 0.3.x of this project I get:

![screen shot 2015-04-04 at 3 21 31 pm](https://cloud.githubusercontent.com/assets/368057/6994891/85c63c14-dade-11e4-8cb6-131d60de86e8.png)

But if I `pip install --upgrade guzzle_sphinx_theme` the default is now:

![screen shot 2015-04-04 at 3 16 58 pm](https://cloud.githubusercontent.com/assets/368057/6994893/9ad33ada-dade-11e4-9f67-1fa1ed4e7590.png)

To get the sidebar back I had to add:

```
html_sidebars = {
    '**': ['logo-text.html', 'globaltoc.html', 'searchbox.html']
}
```

which then gives me what I was looking for:

![screen shot 2015-04-04 at 3 18 59 pm](https://cloud.githubusercontent.com/assets/368057/6994907/effa5e62-dade-11e4-8881-8ea06e8cced6.png)

It would be great to either:

1. Add back support for showing the sidebar by default like in the built in sphinx theme and v0.3.x of this theme (my preference)
2. Document how people can get the sidebar added if the want it.

**Comment by mtdowling** [comment]
I think we need to add a similar check to this theme: https://bitbucket.org/birkenfeld/sphinx/src/72dceb35264e9429c8d9bb1a249a638ac21f0524/sphinx/themes/basic/layout.html?at=default#cl-64
