### ISSUE TITLE
Sidebar table of contents with 3 levels

### ISSUE THREAD

**Issue by arximboldi** [guzzle/guzzle_sphinx_theme#22]
Hi!

This is a beautiful theme, thanks a lot for making this easily available.

My only complaint is that it would be nice to get three levels of depth in the sidebar table of contents. At the momment, it only show `sections` and `subsections`, but it would be nice if there was a way to make `subsubsections`  reachable from there. The [read the docs theme](https://github.com/snide/sphinx_rtd_theme) supports this feature.

Otherwise, could you maybe hint me at how could I achieve this feature via custom layouts?

Thanks!

**Comment by numrut** [comment]
Hi, @arximboldi!

You should create a `_template` folder in your project directory, place there file `globaltoc.html` from Guzzle Sphinx Theme and change the `maxdepth` value in that file.

**Comment by arximboldi** [comment]
@numrut That is a good workaround! It would be nice if they were collapsable, like in the ReadTheDocs theme, but this is a good start (I could maybe achieve the later playing with the CSS)

**Comment by mgeier** [comment]
I've just created PR #42, which should fix this issue.
