### ISSUE TITLE
Is there a way to customise the css?

### ISSUE THREAD

**Issue by MichaelClerx** [guzzle/guzzle_sphinx_theme#30]
Hi all. Thanks for the lovely theme!

Is there a way to customise/tweak the css? I'd like to add a border above the first method in every class (so that it's more clear where the class description ends and the method descriptions start)

**Comment by tristanlins** [comment]
You can place a `custom.css` in your `_static` directory:

```css
@import url("guzzle.css");

/* custom styles here */
```

And use this in your `conf.py`: `html_style = 'custom.css'`

**Comment by MichaelClerx** [comment]
Thanks!
